const EN = {
    "Productos": "Products",
    "Buscar libros por palabra clave / título / autor": "Search books by keyword / title / author",
    "Ordenar": "Order",
    "Precio menor a mayor": "Price lower to higher",
    "Precio mayor a menor": "Price higher to lower",
    "Más antiguos": "Oldest",
    "Más recientes": "Most recent",
    "Animales y naturaleza": "Animals and nature",
    "Animales": "Animals",
    "Ciencia": "Sciencie",
    "Ciencia ficción": "Science fiction",
    "Ficción": "Fiction",
    "Cocina": "Cookbooks",
    "Comics": "Comics",
    "Computación y tecnología": "Technology",
    "Tecnología": "Technology",
    "Deportes": "Sports",
    "Derecho": "Law",
    "Educación": "Education",
    "Filosofía": "Philosophy",
    "Historia": "History",
    "Matemática": "Maths",
    "Novela": "Novel",
    "Política": "Politics",
    "Fecha de publicación": "Published date",
    "Número de páginas": "Number of pages",
    "ver más": "view more",
    "ver menos": "view less",
    "Libro añadido al carrito": "Book added to cart",
    "Leer online": "Read online",
    "No esta a la venta": "Not on sale",
    "Detalles del carrito": "Cart details",
    "Cantidad": "Quantity",
    "Eliminar": "Remove",
    "TOTAL": "TOTAL",
    "Proceder al pago": "Proceed to payment",
    "No se encontraron libros. Ingrese otro término de busqueda.": "No books found. Try another search term."
}

export default EN
