const PT = {
    "Productos": "Produtos",
    "Buscar libros por palabra clave / título / autor": "Pesquisar livros por palavra-chave/título/autor",
    "Ordenar": "Ordem",
    "Precio menor a mayor": "Preço mais baixo para mais alto",
    "Precio mayor a menor": "preço mais alto para o mais baixo",
    "Más antiguos": "Mais velho",
    "Más recientes": "Mais recente",
    "Animales y naturaleza": "Animais e Natureza",
    "Ciencia": "Ciência",
    "Ciencia ficción": "Ficção cientifica",
    "Cocina": "Cozinha",
    "Comics": "Comics",
    "Computación y tecnología": "Informática e Tecnologia",
    "Deportes": "Esportes",
    "Derecho": "Direito",
    "Educación": "Educação",
    "Filosofía": "Filosofia",
    "Historia": "História",
    "Matemática": "Matemática",
    "Novela": "Romance",
    "Política": "Política",
    "Fecha de publicación": "Data de publicação",
    "Número de páginas": "Número de páginas",
    "ver más": "Ver mais",
    "ver menos": "Ver menos",
    "Libro añadido al carrito": "Livro adicionado ao carrinho",
    "Leer online": "Leia online",
    "No esta a la venta": "Não está a venda",
    "Detalles del carrito": "Detalhes do Carrinho",
    "Cantidad": "Quantia",
    "Eliminar" : "Eliminar",
    "TOTAL": "TOTAL",
    "Proceder al pago": "Prossiga para o pagamento",
    "No se encontraron libros. Ingrese otro término de busqueda.": "Nenhum livro encontrado. Digite outro termo de pesquisa."
}

export default PT